In [3]:
import pandas as pd
import numpy as np
#!pip install openpyxl# python requores this openpyxl library to open xlsx files

In [16]:
data = pd.read_csv(r"Loan_default_1500.csv")

data = data[['Credit_Score', 'income', 'loan_amount', 'dtir1', 'Status']]
data.head()

   Credit_Score   income  loan_amount  dtir1  Status
0           758   1740.0       116500   45.0       1
1           552   4980.0       206500    NaN       1
2           834   9480.0       406500   46.0       0
3           587  11880.0       456500   42.0       0
4           602  10440.0       696500   39.0       0

In [17]:
data.isna().sum()
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1509 entries, 0 to 1508
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Credit_Score  1509 non-null   int64
 1   income        1407 non-null   float64
 2   loan_amount   1509 non-null   int64
 3   dtir1         1259 non-null   float64
 4   Status        1509 non-null   int64
dtypes: float64(2), int64(3)
memory usage: 59.1 KB

In [18]:
data['Credit_Score'].fillna(data['Credit_Score'].mean(), inplace=True)
data['income'].fillna(data['income'].median(), inplace=True)
data['loan_amount'].fillna(data['loan_amount'].mean(), inplace=True)
data['dtir1'].fillna(data['dtir1'].mean(), inplace=True)

C:\Users\Tetra\AppData\Local\Temp\ipykernel_20108\3774895047.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['Credit_Score'].fillna(data['Credit_Score'].mean(), inplace=True)
C:\Users\Tetra\AppData\Local\Temp\ipykernel_20108\3774895047.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['income'].fillna(data['income'].median(), inplace=True)
C:\Users\Tetra\AppData\Local\Temp\ipykernel_20108\3774895047.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['loan_amount'].fillna(data['loan_amount'].mean(), inplace=True)
C:\Users\Tetra\AppData\Local\Temp\ipykernel_20108\3774895047.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['dtir1'].fillna(data['dtir1'].mean(), inplace=True)

0       45.000000
1       38.162033
2       46.000000
3       42.000000
4       39.000000
          ...
1504    44.000000
1505    38.162033
1506    26.000000
1507    38.000000
1508    39.000000
Name: dtir1, Length: 1509, dtype: float64

In [7]:

data.info()
data.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Credit_Score  499 non-null    int64
 1   income        465 non-null    float64
 2   loan_amount   499 non-null    int64
 3   dtir1         412 non-null    float64
 4   Status        499 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 19.6 KB

Credit_Score     0
income          34
loan_amount      0
dtir1           87
Status           0
dtype: int64

In [19]:
data['income'] = data['income'].fillna(data['income'].median())
data['dtir1'] = data['dtir1'].fillna(data['dtir1'].median())

In [20]:
data.isna().sum()

Credit_Score    0
income          0
loan_amount     0
dtir1           0
Status          0
dtype: int64

In [10]:
# now the data is ready to be trained by linear regression model

In [21]:
data

      Credit_Score   income  loan_amount  dtir1  Status
0              758   1740.0       116500   45.0       1
1              552   4980.0       206500   40.0       1
2              834   9480.0       406500   46.0       0
3              587  11880.0       456500   42.0       0
4              602  10440.0       696500   39.0       0
...            ...      ...          ...    ...     ...
1504           533   5880.0       236500   44.0       0
1505           834   2700.0       196500   40.0       1
1506           624   2340.0       116500   26.0       1
1507           840   3000.0       136500   38.0       0
1508           555   4080.0       176500   39.0       0

[1509 rows x 5 columns]

In [22]:
data.to_csv("cleaned_csv.csv")